import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: ['index', 'generated/getting-started', 'guides/environments', 'guides/mcp',
    'guides/terminal', 'guides/judge', 'generated/bundled-cli',
    'generated/ubuntu', 'guides/releases'],
  commands: [{type: 'autogenerated', dirName: 'generated/reference'}],
  developers: ['guides/architecture', 'guides/development', 'guides/deployment',
    'generated/stable', 'generated/preview', 'generated/terminal-preview'],
};
export default sidebars;
