import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    'index', 'generated/getting-started',
    {type: 'category', label: 'Architecture and deployment', items: [
      'guides/architecture', 'platform/deployment', 'guides/skills']},
    {type: 'category', label: 'Configuration', items: [
      'configuration/gateway', 'configuration/keycloak', 'configuration/entra',
      'configuration/mcp', 'guides/environments']},
    {type: 'category', label: 'Validation', items: ['validation/acceptance']},
    {type: 'category', label: 'Hands-on operations', items: [
      'operations/cheat-sheet', 'generated/sso-servicenow', 'guides/terminal', 'guides/mcp', 'guides/judge',
      'generated/bundled-cli', 'generated/ubuntu']},
    'guides/releases',
  ],
  commands: [{type: 'autogenerated', dirName: 'generated/reference'}],
  developers: ['guides/development', 'guides/deployment',
    'generated/stable-014', 'generated/stable-013', 'generated/stable', 'generated/preview', 'generated/terminal-preview'],
};
export default sidebars;
